
ARTIFACT="dist/build/logparser/logparser".freeze

desc "Clean build artifacts"
task :clean do
  cabal 'clean'
end

desc "Create the logparser binary"
task :build => :clean do
  %w(configure build).each do |cmd|
    cabal cmd
  end
  `strip #{ARTIFACT}`
end

desc "Build and package the logparser"
task :package => :build do
  `tar zfc logparser-#{RUBY_PLATFORM}-#{version}.tar.gz LICENSE NOTICE -C.. README.md -Clogparser/dist/build/logparser logparser`
end

desc "Rebuild and copy the logparser into the cabal bin directory"
task :rebuild => :build do
  cabal 'copy'
end


desc "Run the tests"
task :test do
  ["clean", "configure --enable-tests", "build", "test"].each do |cmd|
    cabal cmd
  end
end

def version
  `git describe --tag --always`.strip
end

def cabal(cmd)
  print `cabal #{cmd}`
end
